# Site settings
title: Jessye Ejdelman
description: >-
  Software engineer, language-nerd, and lover of geography. Get to know me at <a href="https://github.com/ejdelsztejn" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: America/New_York
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/ejdelsztejn/ejdelsztejn.github.io
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Jessye Ejdelman
  bio: >-
    Software engineer, language-nerd, and lover of geography. Get to know me at <a href="https://github.com/ejdelsztejn" target="_blank" rel="noopener">@github</a>.
  username: ejdelsztejn
  email: jessye.ejdelman@gmail.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: "ejdelsztejn.github.io"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
